services:
  directus:
    build:
      context: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 127.0.0.1:8055:8055
    environment:
      LOG_LEVEL: "trace"
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: "5432"
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin
      ADMIN_TOKEN: token_admin

  db:
    image: docker.io/library/postgres:17
    security_opt:
      - no-new-privileges=true
    environment:
      POSTGRES_USER: directus
      POSTGRES_DB: directus
      POSTGRES_PASSWORD: directus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d directus"]
      interval: 30s
      timeout: 10s
      retries: 5
