name: Build and publish
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: generate_website
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # From https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Generate website
        run: cargo run --verbose
        env:
          WTECH_BASE_URL: ${{ vars.WTECH_BASE_URL }}
          WTECH_API_BASE_URL: ${{ vars.WTECH_API_BASE_URL }}
          WTECH_API_KEY: ${{ secrets.WTECH_API_KEY }}

      - name: Publish to VPS
        if: github.event_name != 'pull_request'
        run: |
          # Trust SSH host keys
          mkdir -p ~/.ssh/
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          curl 'https://raw.githubusercontent.com/JenswBE/setup/main/server/files/po/rsyncd-public-keys.txt' >> ~/.ssh/known_hosts

          # Setup SSH key
          touch ssh_key
          chmod 600 ssh_key
          echo '${{ secrets.SSH_KEY }}' > ssh_key

          # Sync generated files
          rsync --verbose --archive --delete --rsh='ssh -p ${{ vars.SSH_PORT }} -i ssh_key' output/ ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:/
